### ISSUE TITLE
Parsing Src_IP from logs to geo-locate events

### ISSUE THREAD

**Issue by craiglawson** [dsvetlov/lightsiem#13]
I am struggling to get the source IP to parse from the message, My aim of this is to then geo-locate the IP on a map so you can easily see to a view where traffic is originating from.

I have already enabled geo-location in OSSEC as per - http://blog.rootshell.be/2012/06/05/attackers-geolocation-in-ossec/ and the alerts.log now has a Src IP and Src Location in the alert messages.

I have previously got this working using the OSSEC + ELK VM provided by OSSEC, but can't get it working with LightSIEM... :(

FYI - I added this to logstash.conf on my OSSEC provided VM:

```
geoip {
  source => "Src_IP"
  target => "geoip"
  add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
  add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
}
```

Thanks,

Craig

**Comment by dsvetlov** [comment]
Hi, Craig!

Thanks a lot for interest in my project!

Geo location of ip can be achieved via Logstash plugin. It have already done for Snort logs. Now I add geo location for OSSEC logs and map on main dashboard.

Hope you are enjoy.)))

**Comment by craiglawson** [comment]
Hi Daniil, as we discussed, here are some samples once I commented out the following line - remove_field => [ "message" ]":

Event Type - "SSHD Authentication Success" (this displays the expected IP in the Alert.Source.Node.Address & Alert.Source.Node.Geoip.ip fields):

[removed this message string, I realise it works because I logged into the OSSEC server direct not a hybrid box...]

Event type - "Multiple Firewall drop events from same source." (this displays the OSSEC Hybrid servers IP in the Alert.Source.Node.Address & Alert.Source.Node.Geoip.ip fields)

message: <132>Apr 30 22:35:14 ossec ossec: Alert Level: 10; Rule: 4151 - Multiple Firewall drop events from same source.; Location: (_HOSTNAME_-LOGS) 81.201.xxx.xxx->/var/ossec/logs/alerts/alerts.log|_HOSTNAME_-LOGS->172.29.xxx.xxx; srcip: 123.196.116.66; srccity: CN,Beijing,Beijing; Apr 30 2015 18:56:51: %ASA-4-106023: Deny tcp src outside:123.196.116.66/15193 dst PCI_INSIDE:172.30.xxx.xxx/22 by access-group "acl_out" [0x0, 0x0]

81.201.xxx.xxx is the OSSEC Hybrid server
_HOSTNAME_-LOGS has been anonymised

srcip: 123.196.116.66 is the IP field I want to extract

Thanks for your help with this

**Comment by craiglawson** [comment]
By adding the following line to "20-ossec.conf":

grok {
  match => { "message" => "srcip: %{IP:Originating.IP}" }
}

I am now able to extract the IP from the message, does this seem like a suitable way of extracting the information? I'm not sure what naming scheme you would prefer to use so I used Originating.IP in my test.

By editing this section to:

geoip {
   source => "Originating.IP"
   target => "Alert.Source.Node.Geoip"
}

My world map is being populated! :)

**Comment by craiglawson** [comment]
This isn't a perfect solution either, as those events without a srcip are tagged "_grokparsefailure". It's a bit of a hack but would something like this be suitable?

tag_on_failure => [ "no srcip" ] 

(or suitable wording to that effect)

**Comment by dsvetlov** [comment]
@craiglawson, can you please check now parsing of alerts for hybrid server? I have make some changes in patterns for OSSEC. I think it will help. But it will require dashboard editing. I parsing is OK, I will post changes in dashboard.

And one more question. I think, same problem will appear with syscheck and ossec-monitor alerts. Can you post some samples of this alerts?

**Comment by craiglawson** [comment]
@dsvetlov Sorry about the delay coming back to you, I've just updated my install, this is looking good, so the remote address should be "Alert.Source.Node.Address" now?

I haven't observed any syscheck  alerts with _grokparsefailures tags, I will check up on it tomorrow and report back

**Comment by dsvetlov** [comment]
Syscheck can be matched by wrong pattern. Just try to change file under FIM.

**Comment by craiglawson** [comment]
I have just seen this, it caught my eye as it was listed as "Alert.Sensor.Node.Name ossec" (ossec is the central server name), when I looked at the message though it was not from this server, see the full message below:

<132>May  6 15:30:07 ossec ossec: Alert Level: 2; Rule: 1002 - Unknown problem somewhere in the system.; Location: ossec->/var/log/messages|ossec->/var/log/messages|ossec->/var/log/messages|ossec->/var/log/messages|ossec->/var/log/messages|ossec->/var/log/messages|ossec->/var/log/messages|ossec->/var/log/messages|(HOSTNAME-LOGS) 81.201.xxx.xxx->/var/ossec/logs/alerts/a; +.NET4.0E) 200 0\xC0#\x80#003

Think I will query the repeated "ossec->/var/log/messages|" this to the ossec-list...

**Comment by dsvetlov** [comment]
@craiglawson seems like this message circulate inside ossec server few times.
