### ISSUE TITLE
Missing Alert.Target.File.Path fields on fim.json

### ISSUE THREAD

**Issue by craiglawson** [dsvetlov/lightsiem#20]
Seems that since our recent updates the fim.json dashboard is not displaying the file paths correctly from hybrid servers, the data appears to be there in the message field, but no "Alert.Target.File.Path field" is present.

This occurs if I change a file on a remote host via hybrid server or on a directly attached ossec agent.

**Comment by dsvetlov** [comment]
Hi, Craig!

Can you provide log sample? I will check patterns and make patch.

**Comment by craiglawson** [comment]
Hi Daniil,

Here is a log sample taken from the message field:

<132>May 15 07:28:47 ossec ossec: Alert Level: 7; Rule: 550 - Integrity checksum changed.; Location: (CL-ubuntu) xxx.xxx.xxx.xxx->syscheck; Previous MD5: '51ad4dca4a61d26f22f928b9dffb9162'; Current MD5: 'c972d3f2b8d3e5362769f686eda4bb23'; Previous SHA1: '35ddd70ec2d203ff496418f5e5414e8674e2a8ea'; Current SHA1: 'fba7e8c6ca44cf40e080ea2052b1687a9c5b1fd2'; Integrity checksum changed for: '/etc/passwd'

**Comment by dsvetlov** [comment]
@craiglawson, I think, fixed. Can you check please?

**Comment by craiglawson** [comment]
Ahh - Yep works perfectly! Thank you very much!

**Comment by dsvetlov** [comment]
@craiglawson, you are always welcome)))

**Comment by craiglawson** [comment]
@dsvetlov I have noticed after a few days of data I am receiving logs perfectly for agents connected directly to the master OSSEC server, but not agents connected to hybrid servers which in turn connect to the master. e.g.

Agent => OSSEC server - works
Agent => OSSEC Hybrid => OSSEC server - not receiving logs in the fim dashboard, missing Alert.Source.Ident field for the syscheck tag

Here is a message from an event via a hybrid server:

<132>May 19 16:42:36 ossec ossec: Alert Level: 7; Rule: 550 - Integrity checksum changed.; Location: (SERVERNAME-LOGS) xxx.xxx.xxx.xxx->/var/ossec/logs/alerts/alerts.log|(SERVERNAME) xxx.xxx.xxx.xxx->syscheck; Integrity checksum changed for: '/etc/selinux/targeted/modules/active/modules/passenger.pp'

SERVERNAME-LOGS is the hybrid server, SERVERNAME is the agent of the hybrid server.

Do logstash patterns work in order? as in, we have the OSSEC_SYSCHECK line already, could this be duplicated but slightly modified for a match with a hybrid box? I'll have a play and report back any findings :)

**Comment by dsvetlov** [comment]
@craiglawson, fixed it in latest commit.
