### ISSUE TITLE
trouble installation in step ansible-playbook lightsiem-master/lightsiem-install.yml

### ISSUE THREAD

**Issue by simpleuser99** [dsvetlov/lightsiem#23]
When i start "ansible-playbook lightsiem-master/lightsiem-install.yml"
I have a next report:

PLAY [Install and configure Elasticsearch, Logstash, Kibana] ******************

TASK: [elk | Install packages] ************************************************
ok: [localhost] => (item=java,http://download.elastic.co/logstash/logstash/packages/centos/logstash-1.5.0-1.noarch.rpm,https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.4.noarch.rpm,epel-release,nodejs,unzip,npm)

TASK: [elk | Open port in firewalld for Logstash OSSEC input] *****************
failed: [localhost] => {"failed": true, "parsed": false}
BECOME-SUCCESS-rmnhowxxyowmvaqgqhmfzdynjkowobjn
failed=True msg='firewalld required for this module'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/lightsiem-install.retry

localhost                  : ok=1    changed=0    unreachable=0    failed=1

What does it meen? And how can i fix it?

**Comment by dsvetlov** [comment]
@simpleuser99, it seems that ansible can't configure firewalld. Wich linux distro do you use? Are firewalld installed and running?

**Comment by dsvetlov** [comment]
I've added ignore_errors option. So, if ansible can't open ports via firewalld it still install other parts of LightSIEM, but you need to open ports by yourself.

**Comment by dsvetlov** [comment]
You need to open 9000, 9010, 9020 UDP and 80 TCP ports.

**Comment by dsvetlov** [comment]
@simpleuser99 , test again, please.

**Comment by simpleuser99** [comment]
Hello. Thank you for help me.
May you help me more please?
I dont understand how it work.
I have OSSEC on my server. I do install steps from
https://github.com/dsvetlov/lightsiem
When I try  "Now point your web-browser to port 80 of your LightSIEM server."
 <ip_address>:80 I didn`t see lightSIEM.
Who is a webserver? When i do "ansible-playbook
lightsiem-master/lightsiem-install.yml", the install script itself create a
webserver?
 I`m very grateful for your help.

2015-05-23 18:12 GMT+03:00 dsvetlov notifications@github.com:

**Comment by dsvetlov** [comment]
@simpleuser99 , which Linux distro you are using?
Kibana Authentication proxy is node.is application that creates web-server.

**Comment by simpleuser99** [comment]
## I use centos 6.6

Отправлено из Mail.Ru для Android
понедельник, 25 мая 2015г., 20:07 +04:00 от dsvetlov notifications@github.com:

**Comment by dsvetlov** [comment]
@simpleuser99, can you setup server with centos 7? Playbook designed for using only with CentOS7.

**Comment by simpleuser99** [comment]
## Unfortunately, It is impossible for me. I can't using it on CentOS 6.6? 

Отправлено из Mail.Ru для Android
понедельник, 25 мая 2015г., 21:14 +04:00 от dsvetlov notifications@github.com:

**Comment by dsvetlov** [comment]
@simpleuser99 , try to run "/usr/bin/node /opt/kibana-authentication-proxy/app.js" from console. It will run node application,  that will serve on 80 port.

**Comment by simpleuser99** [comment]
Ok, I run it
/usr/bin/node /opt/kibana-authentication-proxy/app.js
Server starting...
Warning: No basic authentication presented
Warning: No Google OAuth2 presented
Warning: No CAS authentication presented
Server listening on 9201

But, if I do "point your web-browser to port 80 of your LightSIEM server"
it didn`t  work, i see "ERR_CONNECTION_REFUSED"

2015-05-25 23:51 GMT+03:00 dsvetlov notifications@github.com:

**Comment by dsvetlov** [comment]
@simpleuser99, as server writes, it listening on port 9091. I think it's because Playbook not place proper configs. Did you rerun Playbook after failure?

**Comment by simpleuser99** [comment]
Yes, I rerun. But now I repeat it. At first, I downloaded master.zip. "wget
https://github.com/dsvetlov/lightsiem/archive/master.zip"
than, I unziped "unzip master.zip" and try to rerun Playbook:

ansible-playbook lightsiem-master/lightsiem-install.yml

PLAY [Install and configure Elasticsearch, Logstash, Kibana]

---

TASK: [elk | Install packages]

---

ok: [localhost] => (item=java,
http://download.elastic.co/logstash/logstash/packages/centos/logstash-1.5.0-1.noarch.rpm,https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.4.noarch.rpm,epel-release,nodejs,unzip,npm
)

TASK: [elk | Open port in firewalld for Logstash OSSEC input]

---

failed: [localhost] => {"failed": true, "parsed": false}
BECOME-SUCCESS-jyevxnymkixhglbwktpwxllmxdjbicem
failed=True msg='firewalld required for this module'

...ignoring

TASK: [elk | Place Logstash patterns file for ossec]

---

ok: [localhost]

TASK: [elk | Open port in firewalld for Logstash Snort input]

---

failed: [localhost] => {"failed": true, "parsed": false}
BECOME-SUCCESS-susypbhpqoidvgxnjmoqkgovlibqhwoq
failed=True msg='firewalld required for this module'

...ignoring

TASK: [elk | Open port in firewalld for Logstash Snort full via lumberjack
input] ***
failed: [localhost] => {"failed": true, "parsed": false}
BECOME-SUCCESS-zrwzhpnbrigwzglfehghidnpwzgtjadh
failed=True msg='firewalld required for this module'

...ignoring

TASK: [elk | Place Logstash patterns file for snort]

---

ok: [localhost]

TASK: [elk | Place Logstash patterns file for IDMEF]

---

ok: [localhost]

TASK: [elk | Place Logstash patterns file for Cisco]

---

changed: [localhost]

TASK: [elk | Place Logstash input config for ossec]

---

ok: [localhost]

TASK: [elk | Place Logstash input config for snort]

---

changed: [localhost]

TASK: [elk | Place Logstash input config for Cisco]

---

changed: [localhost]

TASK: [elk | Open port in firewalld for Logstash Cisco input]

---

failed: [localhost] => {"failed": true, "parsed": false}
BECOME-SUCCESS-jqpzyzytpzkyvbwqlvlblhpcrdfrzwms
failed=True msg='firewalld required for this module'

...ignoring

TASK: [elk | Place Logstash common config]

---

ok: [localhost]

TASK: [elk | Place Logstash output config for elasticsearch]

---

ok: [localhost]

TASK: [elk | Place Logstash template for elasticsearch output]

---

ok: [localhost]

TASK: [elk | Add logstash to autostart]

---

changed: [localhost]

TASK: [elk | Place Elasticsearch config file]

---

ok: [localhost]

TASK: [elk | Add elasticsearch to autostart]

---

changed: [localhost]

TASK: [elk | Download Kibana Authentication Proxy]

---

ok: [localhost]

TASK: [elk | Unzip Kibana Authentication Proxy]

---

changed: [localhost]

TASK: [elk | Rename Kibana Authentication Proxy folder]

---

changed: [localhost]

TASK: [elk | Download Kibana 3]

---

ok: [localhost]

TASK: [elk | Unzip Kibana 3]

---

changed: [localhost]

TASK: [elk | Rename Kibana 3 folder]

---

changed: [localhost]

TASK: [elk | Install Express module for Node.js]

---

changed: [localhost]

TASK: [elk | A litle patch Kibana]

---

changed: [localhost]

TASK: [elk | Open port in firewalld for Kibana]

---

failed: [localhost] => {"failed": true, "parsed": false}
BECOME-SUCCESS-qjoknhrkeyaibkrwqnzhnifahzeiqpzw
failed=True msg='firewalld required for this module'

...ignoring

TASK: [elk | Place systemd unit file for Kibana]

---

failed: [localhost] => {"checksum":
"24573cbc6018577392ad4e3f19c3b86e94999918", "failed": true}
msg: Destination directory /etc/systemd/system does not exist

FATAL: all hosts have already failed -- aborting

PLAY RECAP

---

```
       to retry, use: --limit @/root/lightsiem-install.retry
```

localhost                  : ok=27   changed=11   unreachable=0    failed=1

I saw a firewalld error, but CentOS 6.6. don`t have  firewalld daemon. The
one have iptables.
Finally, I rerun node application
/usr/bin/node /opt/kibana-authentication-proxy/app.js
Server starting...
Warning: No basic authentication presented
Warning: No Google OAuth2 presented
Warning: No CAS authentication presented
Server listening on 9201

I didn`t see result on browser port 80 and port 9201

2015-05-26 9:50 GMT+03:00 dsvetlov notifications@github.com:

**Comment by dsvetlov** [comment]
@simpleuser99, I have made small change on playbook.  Now it must run on CentOS 6.x properly, but you need to run manually kibana-authentication proxy. I will write init script for that scenario in 1-2 week. If you will write init scripts, feel free to commit t here.

Aanyway, I'm from Russia too. Если хотите, можете связаться со мной через hangouts или skype.

**Comment by simpleuser99** [comment]
Yes, please chat me on hangouts simplebox66@gmail.com
Thanks

**Comment by dsvetlov** [comment]
@simpleuser99 , I have write you. Did you receive my messages?
