### ISSUE TITLE
lightSIEM Requirment

### ISSUE THREAD

**Issue by saidiahd** [dsvetlov/lightsiem#36]
Hi Folk,
I'm asking about what lightSIEM need (OS version, kernel version, applications, libs ..) . Is it work fine with CentOs 6.7, kernel version:  2.6.32-573.12.1.el6.x86_64 ? 

Thanks

**Comment by dsvetlov** [comment]
Hi, Said!

I believe it can work fine on CentOS 6.7, but installation script is optimized for Cent OS 7. Anyway you can install all components by yourself.
